added openai-rev package
xtekky/gpt4free pull request #218
Opened 2023-04-27 21:23 UTC by sudouser777

1. added wrapper module for using all API's
2. moved all sub-packages(quora, you and theb etc..) inside openai_rev

2023-04-27 22:01 UTC, sudouser777 commented
@xtekky I have tested the changes by installing the package locally, you can test once before merging
once you merge the changes, we can add github action to publish the package

2023-04-27 22:19 UTC, AymaneHrouch requested changes
Can you add `pydantic` to requirements please?

2023-04-27 22:19 UTC, AymaneHrouch commented on openai_rev/openai_rev.py
> +        return ''.join(theb.Completion.create(prompt=prompt))
You're not using `cls`, can you make it staticmethod instead of classmethod?

2023-04-27 22:19 UTC, AymaneHrouch commented on openai_rev/openai_rev.py
>      def __fore_front_service(cls, prompt: str, **kwargs) -> str:
Same here

2023-04-27 22:19 UTC, AymaneHrouch commented on openai_rev/theb/__init__.py
> +    def request(cls, prompt: str):
Same.

2023-04-28 00:01 UTC, xtekky commented
hi will look at this tmrw

2023-04-28 08:16 UTC, sudouser777 commented
> Can you add `pydantic` to requirements please?

@AymaneHrouch pydantic is already there in requirements

2023-04-28 08:23 UTC, sudouser777 commented on openai_rev/theb/__init__.py
> +    def request(cls, prompt: str):
updated

2023-04-28 08:32 UTC, AymaneHrouch approved these changes

2023-04-28 23:07 UTC, xtekky commented
Hi, idk if this is a lot asked, but could you please update files and make a nice documentation, will work on it tmrw, and name package `gpt4free`.

2023-04-29 08:52 UTC, sudouser777 commented
@xtekky I'm closing the pull request, a lot of conflicts and duplicated files because of packaging changes

2023-04-29 08:53 UTC, closed without merging