Update:Make streaming responses more like the OpenAI API.
xtekky/gpt4free pull request #706
Opened 2023-06-30 03:10 UTC by kncxstudio

Update:Make streaming responses more like the OpenAI API.

2023-07-08 23:06 UTC, nacho00112 commented
Why you didn't used the `string` standard library to generate the `completion_id`?

2023-07-18 11:48 UTC, iloveyumyumshrimpnoodles commented
> Why you didn't used the `string` standard library to generate the `completion_id`?

Why import another entire library, just for a few characters?

2023-08-12 11:43 UTC, w3bdesign commented on interference/app.py
> +            response = ChatCompletion.create(provider=Provider.You, model=model, stream=streaming,
Why hardcode model here?

2023-08-12 11:43 UTC, w3bdesign requested changes
Why hardcode model?

2023-08-16 16:05 UTC, closed without merging