Fixed Equing non-streaming request error and added encoding and temperature settings.
xtekky/gpt4free pull request #832
Opened 2023-08-22 07:14 UTC by zeng-rr

2023-08-22 11:01 UTC, Luneye requested changes
non-streaming response is already handled somewhere else and should not be handled inside providers create_completion functions. Take a look at Vercel model. Here is how it could get modified to fix the whole:
[Equing.txt](https://github.com/xtekky/gpt4free/files/12408021/Equing.txt)

2023-08-22 11:02 UTC, Luneye approved these changes

2023-08-22 14:36 UTC, merged

2023-08-23 23:32 UTC, johnd0e commented
But it still does not work with stream=True:
```
Traceback (most recent call last):
  File "D:\AI\gpt4free\stream.py", line 13, in <module>
    for message in response:
  File "D:\AI\gpt4free\g4f\Provider\Equing.py", line 63, in create_completion
    line_json = json.loads(line.decode('utf-8').split('data: ')[1])
IndexError: list index out of range
```

2023-08-23 23:35 UTC, johnd0e commented
@xtekky [Equing.txt](https://github.com/xtekky/gpt4free/files/12408021/Equing.txt) from @Luneye works for me.